// ==========================================
// 1. DICTIONARY & UI INJECTION
// ==========================================
const termDictionary = {
    "hsrp": "Hot Standby Router Protocol. A Cisco-proprietary FHRP that uses an Active/Standby router model.",
    "vrrp": "Virtual Router Redundancy Protocol. An open-standard IEEE FHRP identical to HSRP, but works on any vendor's hardware.",
    "glbp": "Gateway Load Balancing Protocol. A Cisco-proprietary FHRP that natively load-balances traffic across multiple active routers.",
    "fhrp": "First Hop Redundancy Protocol. A category of protocols that provide default gateway redundancy so networks don't fail if one router dies.",
    "virtual ip": "A phantom IP address shared by multiple physical routers in an FHRP group. PCs use this as their Default Gateway.",
    "virtual mac": "A phantom MAC address generated by HSRP so switches know where to send frames for the Virtual IP.",
    "active router": "The router in an HSRP group that is currently forwarding traffic for the network.",
    "standby router": "The backup router in an HSRP group that waits silently. It takes over if the Active router crashes.",
    "priority": "A number (0-255) determining which router becomes Active. Default is 100. Highest priority wins.",
    "preempt": "A command that allows a router with a higher priority to violently seize the Active role from a lower-priority router.",
    "default gateway": "The IP address a computer uses to send traffic outside of its own local network.",
    "version 2": "HSRP version 2 adds support for IPv6 and expands the group number range up to 4095."
};

const termsArray = Object.keys(termDictionary).sort((a, b) => b.length - a.length);

function autoLinkTextNode(textNode) {
    let text = textNode.nodeValue;
    for (let term of termsArray) {
        const escapedTerm = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const regex = new RegExp(`(^|[^a-zA-Z0-9_-])(${escapedTerm})([^a-zA-Z0-9_-]|$)`, 'i');
        const match = text.match(regex);
        if (match) {
            const beforeChar = match[1]; 
            const matchText = match[2];  
            const matchIndex = match.index + beforeChar.length;
            const beforeText = text.substring(0, matchIndex);
            const afterText = text.substring(matchIndex + matchText.length);
            const parent = textNode.parentNode;
            
            if (beforeText) {
                const beforeNode = document.createTextNode(beforeText);
                parent.insertBefore(beforeNode, textNode);
                autoLinkTextNode(beforeNode); 
            }
            
            const span = document.createElement('span');
            span.className = 'term';
            span.setAttribute('data-term', term);
            span.textContent = matchText;
            parent.insertBefore(span, textNode);
            
            if (afterText) {
                const afterNode = document.createTextNode(afterText);
                parent.insertBefore(afterNode, textNode);
                autoLinkTextNode(afterNode); 
            }
            parent.removeChild(textNode);
            return;
        }
    }
}

function highlightElement(el) {
    const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT, null, false);
    const textNodes =[];
    let node;
    while (node = walker.nextNode()) {
        if (node.parentNode.tagName === 'SPAN' && node.parentNode.classList.contains('term')) continue;
        if (node.parentNode.tagName === 'INPUT' || node.parentNode.classList.contains('terminal-output')) continue;
        textNodes.push(node);
    }
    textNodes.forEach(node => autoLinkTextNode(node));
    attachDictionaryListeners();
}

const overlay = document.createElement('div'); overlay.id = 'dict-overlay';
const panel = document.createElement('div'); panel.id = 'dict-panel';
panel.innerHTML = `<button id="dict-close">&times;</button><h3 id="dict-title">Term</h3><div class="dict-content-box" id="dict-desc"></div>`;
document.body.appendChild(overlay); document.body.appendChild(panel);

const closeSidebar = () => { panel.classList.remove('active'); overlay.classList.remove('active'); };
document.getElementById('dict-close').addEventListener('click', closeSidebar);
overlay.addEventListener('click', closeSidebar);

function attachDictionaryListeners() {
    document.querySelectorAll('.term').forEach(term => {
        const newTerm = term.cloneNode(true);
        term.parentNode.replaceChild(newTerm, term);
        newTerm.addEventListener('click', (e) => {
            const termKey = e.target.getAttribute('data-term').toLowerCase();
            const dictEntry = termDictionary[termKey];
            document.getElementById('dict-title').innerText = e.target.innerText.toUpperCase();
            document.getElementById('dict-desc').innerHTML = dictEntry ? `<strong>${e.target.innerText.toUpperCase()}</strong>: ${dictEntry}` : `<strong>${e.target.innerText.toUpperCase()}</strong>: Description not found.`;
            panel.classList.add('active'); overlay.classList.add('active');
        });
    });
}

// ==========================================
// 2. VIRTUAL HSRP DEVICE ENGINE
// ==========================================
const createDevice = (name) => ({
    name: name, hostname: name, mode: '>',
    interfaces: {
        'g0/1': { hsrpVersion: 1, hsrpGroups: {} }, // For R1
        'g0/0': { hsrpVersion: 1, hsrpGroups: {} }  // For R3
    },
    currentContext:[]
});

const network = {
    R1: createDevice('R1'),
    R3: createDevice('R3')
};

let currentDevice = 'R1';
const outputDiv = document.getElementById('output');
const inputField = document.getElementById('cli-input');
const promptSpan = document.getElementById('prompt');
const diagOutput = document.getElementById('diagnostic-output');

window.switchDevice = function(devName, btn) {
    document.querySelectorAll('.test-btn').forEach(b => {
        if(b.innerText.includes('R1') || b.innerText.includes('R3')){
            b.style.background = '#334155';
        }
    });
    btn.style.background = '#0ea5e9';
    currentDevice = devName;
    let dev = network[currentDevice];
    outputDiv.innerHTML = `<br>--- Console connection to ${dev.name} established ---<br>`;
    if(dev.mode === 'LOGGED_OUT') { outputDiv.innerHTML += `Press RETURN to get started.`; dev.mode = '>'; }
    updatePrompt();
    inputField.focus();
};

function updatePrompt() {
    let dev = network[currentDevice];
    let p = '';
    if (dev.mode === '>') p = `${dev.hostname}>`;
    else if (dev.mode === '#') p = `${dev.hostname}#`;
    else if (dev.mode === 'config') p = `${dev.hostname}(config)#`;
    else if (dev.mode === 'config-if') p = `${dev.hostname}(config-if)#`;
    promptSpan.innerText = p;
}

function printLine(text) { outputDiv.innerHTML += `<br>${text}`; outputDiv.scrollTop = outputDiv.scrollHeight; }

inputField.addEventListener('keypress', function(e) {
    if (e.key === 'Enter') {
        const cmdRaw = this.value; const cmd = cmdRaw.trim().toLowerCase();
        printLine(`${promptSpan.innerText}${cmdRaw}`);
        this.value = ''; processCommand(cmd); updatePrompt(); outputDiv.scrollTop = outputDiv.scrollHeight;
    }
});

function processCommand(cmd) {
    let dev = network[currentDevice];

    if (cmd === '') return;
    if (cmd === 'enable' || cmd === 'en') { dev.mode = '#'; return; }
    if (cmd === 'disable') { dev.mode = '>'; return; }
    if (cmd === 'configure terminal' || cmd === 'conf t') { if (dev.mode === '#') dev.mode = 'config'; else printLine("% Invalid input"); return; }
    if (cmd === 'end') { if (dev.mode.startsWith('config')) dev.mode = '#'; return; }
    if (cmd === 'exit') {
        if (dev.mode === 'config') dev.mode = '#';
        else if (dev.mode.startsWith('config-')) dev.mode = 'config';
        return;
    }

    if (dev.mode === 'config') {
        if (cmd.startsWith('int ') || cmd.startsWith('interface ')) {
            let arg = cmd.replace('interface ', '').replace('int ', '').trim();
            let intName = arg.replace('gigabitethernet', 'g');
            if(!dev.interfaces[intName]) dev.interfaces[intName] = { hsrpVersion: 1, hsrpGroups: {} };
            dev.currentContext = [intName];
            dev.mode = 'config-if'; return;
        }
    }

    if (dev.mode === 'config-if') {
        let port = dev.currentContext[0];
        
        // HSRP Commands Parser
        if (cmd === 'standby version 2') { dev.interfaces[port].hsrpVersion = 2; return; }
        if (cmd.startsWith('standby ')) {
            let parts = cmd.split(' ');
            let grp = parseInt(parts[1]);
            if (!dev.interfaces[port].hsrpGroups[grp]) {
                dev.interfaces[port].hsrpGroups[grp] = { vip: null, priority: 100, preempt: false };
            }
            if (parts[2] === 'ip') dev.interfaces[port].hsrpGroups[grp].vip = parts[3];
            else if (parts[2] === 'priority') dev.interfaces[port].hsrpGroups[grp].priority = parseInt(parts[3]);
            else if (parts[2] === 'preempt') dev.interfaces[port].hsrpGroups[grp].preempt = true;
            return;
        }
    }
    printLine(`% Invalid input detected at '^' marker.`);
}

// ==========================================
// 3. DIAGNOSTIC TESTING ENGINE
// ==========================================
function logMsg(msg, isSuccess = false) { return `<div style="margin-bottom: 5px; color: ${isSuccess ? '#4ade80' : '#f87171'}">${isSuccess ? '✅' : '❌'} ${msg}</div>`; }

function runR1HsrpTest() {
    let R1 = network.R1; let pass = true; let output = `<b style="color:white; font-size:1.1rem; display:block;">Checking R1 HSRP (Active)</b>`;

    let g1 = R1.interfaces['g0/1'] || { hsrpVersion: 1, hsrpGroups: {} };
    if (g1.hsrpVersion === 2) output += logMsg(`HSRP Version 2 enabled on g0/1.`, true); else { output += logMsg(`HSRP Version is still 1. Use 'standby version 2'.`); pass = false; }
    
    let grp = g1.hsrpGroups[1];
    if (grp) {
        output += logMsg(`HSRP Group 1 created.`, true);
        if (grp.vip === '192.168.1.254') output += logMsg(`Virtual IP correctly set to 192.168.1.254.`, true); else { output += logMsg(`Virtual IP missing or incorrect.`); pass = false; }
        if (grp.priority === 150) output += logMsg(`Priority correctly elevated to 150.`, true); else { output += logMsg(`Priority is not 150. R1 will not become Active!`); pass = false; }
        if (grp.preempt) output += logMsg(`Preempt enabled. R1 will seize control.`, true); else { output += logMsg(`Preempt missing! R1 won't take back over if it reboots.`); pass = false; }
    } else { output += logMsg(`HSRP Group 1 is missing on g0/1.`); pass = false; }

    output += pass ? `<br><strong style="color:#4ade80;">RESULT: R1 HSRP CONFIGURED PERFECTLY!</strong>` : `<br><strong style="color:#f87171;">RESULT: ERRORS DETECTED. Review hints above.</strong>`;
    diagOutput.innerHTML = output; diagOutput.className = pass ? 'diag-success' : 'diag-error';
    highlightElement(diagOutput);
}

function runR3HsrpTest() {
    let R3 = network.R3; let pass = true; let output = `<b style="color:white; font-size:1.1rem; display:block;">Checking R3 HSRP (Standby)</b>`;

    let g0 = R3.interfaces['g0/0'] || { hsrpVersion: 1, hsrpGroups: {} };
    if (g0.hsrpVersion === 2) output += logMsg(`HSRP Version 2 enabled on g0/0.`, true); else { output += logMsg(`HSRP Version is still 1. Use 'standby version 2'.`); pass = false; }
    
    let grp = g0.hsrpGroups[1];
    if (grp) {
        output += logMsg(`HSRP Group 1 created.`, true);
        if (grp.vip === '192.168.1.254') output += logMsg(`Virtual IP correctly set to 192.168.1.254.`, true); else { output += logMsg(`Virtual IP missing or incorrect.`); pass = false; }
        if (grp.priority === 100) output += logMsg(`Priority is at default (100).`, true); else { output += logMsg(`Warning: Priority was changed. Leave it at default 100 for Standby.`); pass = false; }
    } else { output += logMsg(`HSRP Group 1 is missing on g0/0.`); pass = false; }

    output += pass ? `<br><strong style="color:#4ade80;">RESULT: R3 STANDBY READY!</strong>` : `<br><strong style="color:#f87171;">RESULT: ERRORS DETECTED. Review hints above.</strong>`;
    diagOutput.innerHTML = output; diagOutput.className = pass ? 'diag-success' : 'diag-error';
    highlightElement(diagOutput);
}

function runFailoverTest() {
    let R1 = network.R1; let R3 = network.R3; let pass = true; let output = `<b style="color:white; font-size:1.1rem; display:block;">Checking FHRP Failover Logic</b>`;
    
    let r1Grp = (R1.interfaces['g0/1'] || {hsrpGroups:{}}).hsrpGroups[1];
    let r3Grp = (R3.interfaces['g0/0'] || {hsrpGroups:{}}).hsrpGroups[1];

    if (!r1Grp || !r3Grp) {
        diagOutput.innerHTML = `<strong style="color:#f87171;">ERROR: Finish configuring both R1 and R3 first!</strong>`;
        diagOutput.className = 'diag-error'; return;
    }

    if (r1Grp.vip === r3Grp.vip && r1Grp.vip === '192.168.1.254') output += logMsg(`Virtual IP matches across both routers.`, true); else { output += logMsg(`Virtual IPs do not match! Split-brain scenario detected.`); pass = false; }
    if (r1Grp.priority > r3Grp.priority) output += logMsg(`R1 Priority (${r1Grp.priority}) > R3 Priority (${r3Grp.priority}). R1 is ACTIVE.`, true); else { output += logMsg(`R1 priority is not higher than R3. R1 is NOT active.`); pass = false; }
    if (r1Grp.preempt) output += logMsg(`R1 Preempt enabled. Redundancy loop secured.`, true); else { output += logMsg(`R1 Preempt missing. Failback will break.`); pass = false; }

    output += pass ? `<br><strong style="color:#4ade80;">RESULT: HIGH AVAILABILITY NETWORK ACHIEVED!</strong>` : `<br><strong style="color:#f87171;">RESULT: REDUNDANCY FAILURE. Review hints above.</strong>`;
    diagOutput.innerHTML = output; diagOutput.className = pass ? 'diag-success' : 'diag-error';
    highlightElement(diagOutput);
}

document.getElementById('test-r1-hsrp').addEventListener('click', runR1HsrpTest);
document.getElementById('test-r3-hsrp').addEventListener('click', runR3HsrpTest);
document.getElementById('test-failover').addEventListener('click', runFailoverTest);

// Cheat Sheet Logic
document.addEventListener('DOMContentLoaded', () => {
    highlightElement(document.getElementById('objectives-box'));
    const cheatBtn = document.getElementById('cheat-btn');
    const cheatModal = document.getElementById('cheat-modal');
    const closeCheatBtn = document.getElementById('close-cheat');
    if (cheatBtn && cheatModal) {
        cheatBtn.addEventListener('click', () => cheatModal.style.display = 'flex');
        closeCheatBtn.addEventListener('click', () => cheatModal.style.display = 'none');
        cheatModal.addEventListener('click', (e) => { if (e.target === cheatModal) cheatModal.style.display = 'none'; });
    }
});

// ==========================================
// ANTI-CHEAT / ANTI-INSPECT MECHANISMS
// ==========================================

// 1. Disable Right-Click (Context Menu)
document.addEventListener('contextmenu', event => event.preventDefault());

// 2. Disable F12, Ctrl+Shift+I, Ctrl+Shift+J, and Ctrl+U
document.onkeydown = function(e) {
    // Disable F12
    if (e.keyCode == 123) {
        return false;
    }
    // Disable Ctrl+Shift+I (Open DevTools)
    if (e.ctrlKey && e.shiftKey && e.keyCode == 'I'.charCodeAt(0)) {
        return false;
    }
    // Disable Ctrl+Shift+J (Open Console)
    if (e.ctrlKey && e.shiftKey && e.keyCode == 'J'.charCodeAt(0)) {
        return false;
    }
    // Disable Ctrl+U (View Source)
    if (e.ctrlKey && e.keyCode == 'U'.charCodeAt(0)) {
        return false;
    }
};